// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/MainAdminPanel.tsx": () => import("../components/mockups/dashboard/MainAdminPanel.tsx"),
  "./components/mockups/dashboard/WebDashboard.tsx": () => import("../components/mockups/dashboard/WebDashboard.tsx")
};
